# Generated by Django 4.1 on 2022-08-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_album', models.CharField(max_length=100)),
                ('numero_musicas', models.IntegerField(max_length=2)),
                ('_data', models.TextField(blank=True, db_column='data')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_artista', models.CharField(max_length=100)),
                ('dt_nasc_artista', models.DateTimeField()),
                ('biografia', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('dt_nasc_usuario', models.DateField()),
                ('nome_usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
