# Generated by Django 4.1.4 on 2022-12-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='conteudo_noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto_noticia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.image'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='texto',
            field=models.TextField(null=True),
        ),
    ]
