# Generated by Django 4.1 on 2022-10-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('data_comentario', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='banda',
            name='capa_banda',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.image'),
        ),
        migrations.AddField(
            model_name='banda',
            name='genero_banda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='link_spotify',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
