# Generated by Django 4.1 on 2022-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo_noticias', models.CharField(max_length=255)),
                ('conteudo_noticia', models.TextField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='album',
            old_name='_data',
            new_name='data',
        ),
    ]
