# Generated by Django 4.1 on 2022-10-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("core", "0002_comentario_banda_capa_banda_banda_genero_banda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="capa_album",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="media.image",
            ),
        ),
    ]
