# Generated by Django 4.1 on 2022-08-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticias_rename__data_album_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda_Grupo',
            fields=[
                ('id_banda', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('integrantes', models.CharField(max_length=255)),
                ('dt_criacao', models.DateField()),
                ('desc_banda', models.TextField(max_length=2500)),
                ('nome_banda', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id_musica', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo_musica', models.CharField(max_length=255)),
                ('tempo_musica', models.TimeField()),
            ],
        ),
    ]
