# Generated by Django 4.1 on 2022-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banda_grupo_musica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='numero_musicas',
            field=models.IntegerField(),
        ),
    ]
