# Generated by Django 4.1 on 2022-10-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("core", "0003_album_capa_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="artista",
            name="foto_artista",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="media.image",
            ),
        ),
    ]
