# Generated by Django 4.1 on 2022-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_album_numero_musicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='artistas',
            field=models.ManyToManyField(related_name='musicas', to='core.artista'),
        ),
    ]
