# Generated by Django 4.1.2 on 2022-10-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_artista_foto_artista"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="data_comentario",
            field=models.DateField(auto_now_add=True),
        ),
    ]
