# Generated by Django 4.1.2 on 2022-10-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comentario_data_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
    ]
