# Generated by Django 4.1.2 on 2022-10-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_usuario_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="telefone",
        ),
    ]
