# Generated by Django 4.1.2 on 2022-10-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_banda_foto"),
        ("core", "0007_remove_usuario_telefone"),
    ]

    operations = []
